### ISSUE TITLE
Order Import Errors

### ISSUE THREAD

**Issue by brettburwell** [onedesign/oneshipstation#34]
Hi guys. 

I'm seeing the following error inside the ShipStation account when importing orders from One ShipStation. 

```
An error occurred attempting to update orders: <!DOCTYPE html> <html xmlns="http://www.w3.org/1999/xhtml" lang="en-US"> <head> <meta http-equiv="X-UA-Compatible" content="IE=edge"> <meta charset="utf-8"> <title>Internal Server Error - Revolution Brewing</title> <link rel="stylesheet" type="text/css" href="https://revbrew.com/cpresources/css/craft.css?d=1498133069"/> <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"> <link rel="appl
```

While trying to debug the issue I noticed that if I delete all but ~25 orders from the store and run the update in ShipStation again the error goes away. 

After some trial and error, I strongly suspect that the error is related to the `OneShipStation_XmlService.php` file trying to process orders that include products that have been permanently deleted from the store _after_ the order was made—and the missing product data is somehow causing the XML file to be malformatted.

I tried to add some logic to the plugin to see if I could address the issue myself, but I'm far from a plugin dev and haven't had much luck. 

I wanted to reach out to see if you think my logic sounds correct? And if so, do you think you might be able to update the plugin to protect against deleted products from blowing up the import process. 

Thanks in advance.

**Comment by brianjhanson** [comment]
Hey @brettburwell! Sorry for the long pause, but I _think_ @mkornatz ended up reaching out to you / chatting with you elsewhere.

Either way, did this ever get fixed? We think it was fixed with https://github.com/onedesign/oneshipstation/blob/bf4bfd403db55c8ecac34144754efa4cd601ba31/controllers/OneShipStation_OrdersController.php#L91 but not 100% sure.

**Comment by brettburwell** [comment]
Thanks for reaching out @brianjhanson. 

Yes, @mkornatz and I connected via Slack a while back. I'm a bum and should have followed up here to confirm that Matt's update fixed the issue. My apologies. 

Matt, thanks again for your help with that. It was much appreciated.

**Comment by brianjhanson** [comment]
all good, obviously it was a good little while before we circled back around as well 😬 Glad it fixed your issue though!
